language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    - CODACY_PROJECT_TOKEN=91c9ba170b1b47ef861200c9f9803d73
    - PYTHONPATH=../
install:
  - pip install codacy-coverage
  - pip install coverage
script:
  - coverage run setup.py test
after_success:
  - coverage combine
  - coverage report
  - coverage xml
    # Only report test coverage to Codacy for one of the builds (with Python 3.4)
  - if [ ! -z "$CODACY_PROJECT_TOKEN" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.4" ] && [ "$TRAVIS_BRANCH" == "master" ]; then python-codacy-coverage -r coverage.xml; fi