language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    - CODACY_PROJECT_TOKEN=91c9ba170b1b47ef861200c9f9803d73
    - PYTHONPATH=../
install:
  - pip install codacy-coverage
script:
  - python -m pytest tests/
  - python-codacy-coverage -r coverage.xml